export default [
    {
        pagePath:"/pages/index/index",
        text:"5v5排位",
        iconPath:"/assets/tabbar/5v5.png",
        selectedIconPath:"/assets/tabbar/5v5-selected.png"
    },
    {
        pagePath:"/pages/fight/index",
        text:"大乱斗",
        iconPath:"/assets/tabbar/fight.png",
        selectedIconPath:"/assets/tabbar/fight-selected.png"
    },
    {
        pagePath:"/pages/arena/index",
        text:"斗魂竞技",
        iconPath:"/assets/tabbar/arena.png",
        selectedIconPath:"/assets/tabbar/arena-selected.png"
    },
    {
        pagePath:"/pages/database/index",
        text:"资料库",
        iconPath:"/assets/tabbar/databases.png",
        selectedIconPath:"/assets/tabbar/databases-selected.png"
    },
    {
        pagePath:"/pages/settings/index",
        text:"设置",
        iconPath:"/assets/tabbar/option.png",
        selectedIconPath:"/assets/tabbar/option-selected.png"
    }
]
