export default [
    {
        pagePath:"/pages/index/index",
        text:"5v5排位",
        iconPath:"/assets/tabbar/5v5.png",
        selectedIconPath:"/assets/tabbar/5v5-selected.png"
    },
    {
        pagePath:"/pages/fight/index",
        text:"大乱斗",
        iconPath:"/assets/tabbar/fight.png",
        selectedIconPath:"/assets/tabbar/fight-selected.png"
    },
    {
        pagePath:"/pages/arena/index",
        text:"斗魂竞技",
        iconPath:"/assets/tabbar/arena.png",
        selectedIconPath:"/assets/tabbar/arena-selected.png"
    },
    {
        pagePath:"/pages/heroes/index",
        text:"英雄",
        iconPath:"/assets/tabbar/hero.png",
        selectedIconPath:"/assets/tabbar/hero-selected.png"
    },
    {
        pagePath:"/pages/equipment/index",
        text:"装备",
        iconPath:"/assets/tabbar/equipment.png",
        selectedIconPath:"/assets/tabbar/equipment-selected.png"
    }
]
